Properly clear ReturnAddressList for aarch64
The memset from ff4802e fails to build since remote_ptr is a non-trivial
type:

ReturnAddressList.h:31:63: error: ‘void* memset(void*, int, size_t)’
   clearing an object of non-trivial type ‘class rr::remote_ptr<void>’;
   use assignment or value-initialization instead [-Werror=class-memaccess]