Use -mgeneral-regs-only instead of saving/restoring XMM
This is cleaner/safer than doing the save/restore dance. We do have to be
careful with header file inclusions --- on my system (Fedora 31) we can't
include stdlib.h with -mgeneral-regs-only:

  In file included from /usr/include/stdlib.h:1013,
                   from /home/roc/rr/rr/src/audit/rtld-audit.c:4:
  /usr/include/bits/stdlib-float.h: In function ‘atof’:
  /usr/include/bits/stdlib-float.h:26:1: error: SSE register return with SSE disabled
     26 | {
        | ^

If this becomes onerous we may have to go back to save/restore.